name: daily_ticket_scrape

on:
  schedule:
    - cron:   '50 19 * * *'

jobs:
  auto-scrape:
    runs-on: ubuntu-latest
    env:
      SEATGEEK_CLIENT_ID: ${{secrets.SEATGEEK_CLIENT_ID}}
      SEATGEEK_CLIENT_SECRET: ${{secrets.SEATGEEK_CLIENT_SECRET}}
      OWM_API_KEY: ${{secrets.OWM_API_KEY}}
      REPO_KEY: ${{secrets.GITHUB_TOKEN}}
      username: github-actions
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        
      - name: Install R
        uses: r-lib/actions/setup-r@v2
        
      - name: Install Packages
        run: |
          R -e 'install.packages("tidyverse")'
          R -e 'install.packages("httr")'
          R -e 'install.packages("data.table")'
          R -e 'install.packages("usethis")'
          R -e 'install.packages("jsonlite")'
          R -e 'install.packages("tidyr")'
      
      - name: daily_scrape
        run: ticket_scrape_function.R
      
      - name: Commit files
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git add daily_data/*
          git commit -m "GH Daily Run $(date)"
          git push origin